[package]
name    = "my-rust-kafka"
version = "0.1.0"
authors = ["Srinivasan, Krishna Prasad<skrishnaprasad@gmail.com>"]
edition = "2018"
build   = "build.rs"

[dependencies]
futures = "0.1"
tokio   = "0.1.21"
clap    = "2.33.0"
openssl = "0.10.0"

    [dependencies.rdkafka]
    version     = "~0.28"
    features    = ["ssl", "sasl"]

[[bin]]
name = "producer"
path = "src/producer.rs"
